[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.24'
optimizer = true
optimizer_runs = 200
via_ir = true

[fuzz]
runs = 10000
max_test_rejects = 100000
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 1000
depth = 50
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[profile.ci]
fuzz = { runs = 50000 }
invariant = { runs = 5000, depth = 100 }

[profile.mutation]
fuzz = { runs = 100000 }
invariant = { runs = 10000, depth = 200 }